[2025-03-24T15:59:41.238+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T15:59:41.244+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: e2e_data_pipeline.process_data manual__2025-03-24T15:59:38.939254+00:00 [queued]>
[2025-03-24T15:59:41.247+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: e2e_data_pipeline.process_data manual__2025-03-24T15:59:38.939254+00:00 [queued]>
[2025-03-24T15:59:41.247+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T15:59:41.251+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_data> on 2025-03-24 15:59:38.939254+00:00
[2025-03-24T15:59:41.255+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=217) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-24T15:59:41.254+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'e2e_data_pipeline', 'process_data', 'manual__2025-03-24T15:59:38.939254+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpr5ihwyqq']
[2025-03-24T15:59:41.255+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask process_data
[2025-03-24T15:59:41.255+0000] {standard_task_runner.py:72} INFO - Started process 218 to run task
[2025-03-24T15:59:41.271+0000] {task_command.py:467} INFO - Running <TaskInstance: e2e_data_pipeline.process_data manual__2025-03-24T15:59:38.939254+00:00 [running]> on host 34d5be02b70d
[2025-03-24T15:59:41.294+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='e2e_data_pipeline' AIRFLOW_CTX_TASK_ID='process_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T15:59:38.939254+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T15:59:38.939254+00:00'
[2025-03-24T15:59:41.294+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T15:59:41.307+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-24T15:59:41.310+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T15:59:41.310+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=e2e_data_pipeline, task_id=process_data, run_id=manual__2025-03-24T15:59:38.939254+00:00, execution_date=20250324T155938, start_date=20250324T155941, end_date=20250324T155941
[2025-03-24T15:59:41.356+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T15:59:41.365+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-24T15:59:41.366+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
